//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MacroComm_HelpDesk
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLogFault
    {
        public int Ref_No { get; set; }
        public string Log_Type { get; set; }
        public string Consumer_Type { get; set; }
        public string Comment { get; set; }
        public Nullable<int> LogID { get; set; }
    }
}
