//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MacroComm_HelpDesk
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblViewLog
    {
        public int LogID { get; set; }
        public Nullable<System.DateTime> DateOpened { get; set; }
        public string Source { get; set; }
        public Nullable<int> Acc_No { get; set; }
        public Nullable<int> Ref_No { get; set; }
        public string Fault_Type { get; set; }
        public string Comment { get; set; }
        public string Consumer_Status { get; set; }
        public string Report { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
        public string Tech_Name { get; set; }
        public string Log_Status { get; set; }
    }
}
